using System.Collections.Generic;

namespace YuguLibrary
{
    namespace Models
    {
        /// <summary>
        /// Calculates targets for enemies to prioritize for certain skills.
        /// </summary>
        /// <remarks>
        /// Enemy hits generate aggro via <see cref="EncounterController.CalculateAggro"/>, and are stored within 
        /// <see cref="aggroShares"/>. The enemies with the highest aggro values are stored in <see cref="topAggros"/> 
        /// for enemy targeting if needed. 
        /// </remarks>
        public class AggroSpread
        {
            #region Variables
            /// <summary>
            /// The aggro value form enemy units that have recently attacked a unit.
            /// </summary>
            /// <remarks>
            /// When a unit is attacked, an aggro value is calculated using the damage inflicted to the defending unit using 
            /// <see cref="EncounterController.CalculateAggro"/>.
            /// </remarks>
            public Dictionary<Unit, float> aggroShares = new Dictionary<Unit, float>();
            #endregion

            #region Functions
            /// <summary>
            /// Inserts or appends to a value in <see cref="aggroShares"/>.
            /// </summary>
            /// <remarks>
            /// Searches for the unit’s key, and adds the given value to the current value stored. If the entry does not 
            /// exist, a new entry is added using the parameters given.
            /// </remarks>
            /// <param name="unit">The attacking unit that generated the aggro.</param>
            /// <param name="value">The amount of aggro that was generated by the attacking unit.</param>
            public void InsertAggro(Unit unit, float value)
            {
                if (aggroShares.ContainsKey(unit))
                {
                    aggroShares[unit] += value;
                }
                else
                {
                    aggroShares.Add(unit, value);
                }
            }

            /// <summary>
            /// Subtracts from an aggro value in <see cref="aggroShares"/>.
            /// </summary>
            /// <remarks>
            /// Searches for the unit’s key, and subtracts the given value from the current value stored.
            /// </remarks>
            /// <param name="unit">The key to search for.</param>
            /// <param name="value">The amount of aggro to subtract from the retrieved entry.</param>
            void RemoveAggro(Unit unit, float value)
            {
                if (aggroShares.ContainsKey(unit))
                {
                    aggroShares[unit] -= value;
                }
            }
            #endregion
        }

    }
}